"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
let age = 30;
console.log("Is age > 18? I predict True.");
console.log(age > 18);
console.log("Is age < 25? I predict False.");
console.log(age < 25);
console.log("Is age >= 30? I predict True.");
console.log(age >= 30);
console.log("Is age <= 30? I predict True.");
console.log(age <= 30);
let isRaining = false;
console.log("Is it raining? I predict False.");
console.log(isRaining);
let isSunny = true;
console.log("Is it sunny? I predict True.");
console.log(isSunny);
